#
# Core configuration
#

baseURL = "/"
languageCode = "en-gb"
DefaultContentLanguage = "en"
enableMissingTranslationPlaceholders = "true"
defaultContentLanguageInSubdir = "true"

rssLimit = 100
Paginate = 20
theme = "hugo-bootstrap"

[permalinks]
  target = "/target/:slug/"
  collection = "/collection/:slug/"

#
# Internationalisation
#

[languages]
  [languages.en]
    languageName = "English"
    title = "The UK Web Archive"
    weight = 1
  [languages.cy]
    languageName = "Cymraeg"
    title = "Archif We y DG"
    weight = 2
    [languages.cy.params]
      [languages.cy.params.navigation]
        help = "Aide"

#
# Menus
#

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Topics & Themes"
    url = "/collection/"
    weight = 2

[[menu.main]]
    name = "Save a UK website"
    url = "/info/nominate"
    weight = 3

[[menu.main]]
    name = "About Us"
    url = "/about"
    weight = 4

[[menu.main]]
   name = "Contact Us"
   url = "/contact"
   weight = 5


#
# Related Content
# (used here to allow back-references to be resolved)
#

[related]
   threshold = 40 # n.b. the default of 80 did not work, and references were not found.
   includeNewer = true
   toLower = false

# Ensures the target_ids listed under a Collection can be known to the Target.
[[related.indices]]
   name = "target_ids"
   weight = 100


# 
# Other parameters
#

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/img/ukwa-2018-onwhite-close.svg"
      standard = "/img/ukwa-2018-onwhite-close.svg"
