#
# Core configuration
#

baseURL = "/"
languageCode = "en-gb"
DefaultContentLanguage = "en"
enableMissingTranslationPlaceholders = "true"
defaultContentLanguageInSubdir = "true"

rssLimit = 100
Paginate = 20
theme = "hugo-bootstrap"

# Google analytics
googleAnalytics = "UA-7571526-1"

# Use this to allow raw HTML in the pages:
[markup.goldmark.renderer]
unsafe = true

# Set up ukwa prefix (legacy of original deployment but that's the URLs we have)
[permalinks]
  info = '/ukwa/info/:filename/'
  # Used to clean up links if we're using static site generation for targets/collections
  target = '/ukwa/target/:slug/'
  collection = '/ukwa/collection/:slug/'

[params]
  mainSections = ["ukwa", "info"]

#
# Internationalisation
#
# Site titles defined here, everything else is in ./i18n/* files.
#

[languages]
  [languages.en]
    languageName = "English"
    title = "The UK Web Archive"
    weight = 1
  [languages.cy]
    languageName = "Cymraeg"
    title = "Archif We y DG"
    weight = 2
  [languages.gd]
    languageName = "Gàidhlig"
    title = "Dachaigh UKWA"
    weight = 3

#
# Menus
#

[[menu.main]]
    name = "home"
    url = "/ukwa/"
    weight = 1

[[menu.main]]
    name = "collectionsTitle"
    url = "/ukwa/collection/"
    weight = 2

[[menu.main]]
    name = "saveAUkWebsite"
    url = "/ukwa/info/nominate"
    weight = 3

[[menu.main]]
    name = "aboutUs"
    url = "/ukwa/info/about"
    weight = 4

[[menu.main]]
   name = "contactUs"
   url = "/ukwa/contact"
   weight = 5


#
# Related Content
# (used here to allow back-references to be resolved)
#

[related]
   threshold = 40 # n.b. the default of 80 did not work, and references were not found.
   includeNewer = true
   toLower = false

# Ensures the target_ids listed under a Collection can be known to the Target.
[[related.indices]]
   name = "target_ids"
   weight = 100


