#
# Core configuration
#

baseURL = "/"
languageCode = "en-gb"
DefaultContentLanguage = "en"
enableMissingTranslationPlaceholders = "true"
defaultContentLanguageInSubdir = "true"

rssLimit = 100
Paginate = 20
theme = "hugo-bootstrap"

# Google analytics
googleAnalytics = "UA-7571526-1"

# Use this to allow raw HTML in the pages:
[markup.goldmark.renderer]
unsafe = true

# Used to clean up links if we're using static site generation for targets/collections
#[permalinks]
#  target = "/target/:slug/"
#  collection = "/collection/:slug/"

#
# Internationalisation
#

[languages]
  [languages.en]
    languageName = "English"
    title = "The UK Web Archive"
    weight = 1
  [languages.cy]
    languageName = "Cymraeg"
    title = "Archif We y DG"
    weight = 2
  [languages.gd]
    languageName = "Gàidhlig"
    title = "Dachaigh UKWA"
    weight = 3

#
# Menus
#

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "topics-and-themes"
    url = "/ukwa/collection/"
    weight = 2

[[menu.main]]
    name = "save-a-uk-website"
    url = "/ukwa/info/nominate"
    weight = 3

[[menu.main]]
    name = "about-us"
    url = "/about"
    weight = 4

[[menu.main]]
   name = "contact-us"
   url = "/ukwa/contact"
   weight = 5


#
# Related Content
# (used here to allow back-references to be resolved)
#

[related]
   threshold = 40 # n.b. the default of 80 did not work, and references were not found.
   includeNewer = true
   toLower = false

# Ensures the target_ids listed under a Collection can be known to the Target.
[[related.indices]]
   name = "target_ids"
   weight = 100


