[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"

[[redirects]]
  from = "/en"
  to = "/en/ukwa"
  force = true

[[redirects]]
  from = "/cy"
  to = "/cy/ukwa"
  force = true

[[redirects]]
  from = "/gd"
  to = "/gd/ukwa"
  force = true

[[redirects]]
  from = "/info/faq"
  to = "/en/ukwa/info/faq"
  force = true

