backend:
  name: git-gateway

media_folder: static/assets/uploads

i18n:
  structure: multiple_files
  locales: [en, cy, gd]
  default_locale: en

collections:
  - label: "Pages"
    name: "pages"
    folder: content/pages
    path: "{{slug}}/index"
    i18n: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'page'}
      - {label: 'URL', name: 'url', widget: 'hidden'}
      
  - name: "info"
    label: "Information"
    folder: content/info
    create: true
    path: "{{slug}}/index"
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: true
    


