backend:
  name: git-gateway

media_folder: static/assets/uploads

i18n:
  structure: single_file
  locales: [en, cy, gd]
  default_locale: en

collections:
  - label: "Pages"
    name: "pages"
    i18n:
      structure: single_file
    files:
      - label: "Homepage"
        name: "homepage"
        file: "_index.md"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: "Body", name: "body", widget: "markdown", i18n: true}
      - label: "Technical Information"
        name: "technical-info"
        file: "content/info/technical/index.md"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: "Body", name: "body", widget: "markdown", i18n: true}
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    i18n: true
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog", i18n: duplicate}
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate}
      - {label: "Featured Image", name: "thumbnail", widget: "image", i18n: duplicate}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number", i18n: duplicate}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}

