backend:
  name: git-gateway
  repo: ukwa/ukwa-site

# https://www.netlifycms.org/docs/configuration-options/?#publish-mode
publish_mode: editorial_workflow

media_folder: static/assets/uploads
public_folder: /assets/uploads

i18n:
  structure: multiple_files
  locales: ["en", "cy", "gd", "un"]
  default_locale: en

collections:
  - name: "homepage"
    label: "Homepage"
    folder: content/ukwa
    create: false
    i18n: true
    preview_path: "en/ukwa/{{dirname}}"
    fields:
      - {label: 'Title', name: 'title', widget: 'string', i18n: true}
      - {label: 'Body', name: 'body', widget: 'markdown', i18n: true}
      - {label: 'Layout', name: 'layout', widget: 'hidden'}
      - {label: 'Aliases', name: 'aliases', widget: 'hidden'}
      - label: "Highlights"
        name: "highlights"
        collapsed: false
        widget: "list"
        min: 3
        max: 3
        fields:
         - {label: "Collection ID Number", name: collectionId, widget: string}
         - {label: "Collection Title", name: collectionTitle, widget: string, i18n: true }
         - {label: "Collection Description", name: collectionDescription, widget: string, i18n: true }
      
  - name: "info"
    label: "Information Page"
    folder: content/info
    create: false
    path: "{{slug}}/index"
    i18n: true
    preview_path: "en/ukwa/info/{{dirname}}"
    fields:
      - {label: 'Title', name: 'title', widget: 'string', i18n: true}
      - {label: 'Body', name: 'body', widget: 'markdown', i18n: true}
      - {label: 'Aliases', name: 'aliases', widget: 'hidden'}
    


