backend:
  name: git-gateway
  repo: ukwa/ukwa-site

# https://www.netlifycms.org/docs/configuration-options/?#publish-mode
publish_mode: editorial_workflow

media_folder: static/assets/uploads
public_folder: /assets/uploads

i18n:
  structure: multiple_files
  locales: ["en", "cy", "gd", "un"]
  default_locale: en

collections:
  - label: "Page"
    name: "page"
    # i18n mode currently only supports single-file transations for file collections
    # So we have separate editors for each
    files:
      - label: "Homepage (EN)"
        name: "homepage_en"
        file: "content/_index.en.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'homepage'}
      - label: "Homepage (CY)"
        name: "homepage_cy"
        file: "content/_index.cy.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'homepage'}
      - label: "Homepage (GD)"
        name: "homepage_gd"
        file: "content/_index.gd.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'homepage'}
      
  - name: "info"
    label: "Information Page"
    folder: content/info
    create: false
    path: "{{slug}}/index"
    i18n: true
    preview_path: "en/ukwa/info/{{dirname}}"
    fields:
      - {label: 'Title', name: 'title', widget: 'string', i18n: true}
      - {label: 'Body', name: 'body', widget: 'markdown', i18n: true}
      - {label: 'Aliases', name: 'aliases', widget: 'hidden'}
    


