backend:
  name: git-gateway

media_folder: static/assets/uploads

i18n:
  structure: multiple_files
  locales: [en, cy, gd]
  default_locale: en

collections:
  - label: "Pages"
    name: "pages"
    # File collections only support single-file mode.
    i18n:
      structure: single_file    
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/_index.md"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: "Body", name: "body", widget: "markdown", i18n: true}
      
  - name: "info"
    label: "Info"
    folder: content/info
    create: false
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: true
    


